## 텐서(TENSOR)

In [1]:
import torch
import numpy as np

## 텐서 초기화하기

### 1. 데이터로부터 직접(directly) 생성하기

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


### 2. NumPy 배열로부터 생성하기

In [3]:
np_array = np.array(data)
np_array

array([[1, 2],
       [3, 4]])

In [4]:
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


### 3. 다른 텐서로부터 생성하기

In [5]:
x_ones = torch.ones_like(x_data)         # x_data의 속성을 유지
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [6]:
x_rand = torch.rand_like(x_data, dtype = torch.float)   # x_data의 속성을 덮어씀
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.4928, 0.7229],
        [0.7712, 0.8317]]) 



In [7]:
# 다른 텐서로부터 생성할 때 dtype을 맞게 바꿔주지 않으면 다른 텐서의 속성을 유지하므로 에러 발생
x_rand_test = torch.rand_like(x_data)   # dtype 설정 X
print(x_rand_test)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

### 4. 무작위(random) 또는 상수(constant) 값을 사용하기

In [8]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.1181, 0.5767, 0.0134],
        [0.2462, 0.1798, 0.4371]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## 텐서의 속성(Attribute)

In [9]:
tensor = torch.rand(3, 4)

print(f"Tensor: \n {tensor} \n")
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Tensor: 
 tensor([[0.9838, 0.0257, 0.8115, 0.5303],
        [0.8659, 0.0520, 0.3315, 0.6309],
        [0.1788, 0.8863, 0.6581, 0.4471]]) 

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 텐서 연산(Operation)

- 텐서 연산 GPU에서 실행

In [10]:
# GPU가 존재하면 텐서를 이동시킴
if torch.cuda.is_available():
    tensor = tensor.to('cuda')  # 텐서 이동 명령어 'to'
    print(f"Device tensor is stored on: {tensor.device}")

In [11]:
print(torch.cuda.is_available())

False


- NumPy식의 표준 인덱싱과 슬라이싱

In [12]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


- 텐서 합치기

In [13]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1.shape)
print(t1)

torch.Size([4, 12])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [14]:
t2 = torch.stack([tensor, tensor, tensor])
print(t2.shape)
print(t2)

torch.Size([3, 4, 4])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


In [15]:
t3 = torch.stack([tensor, tensor, tensor], dim = 1)
print(t3.shape)
print(t3)

torch.Size([4, 3, 4])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


- 텐서 곱하기

In [16]:
# 요소별 곱(element-wise product) 계산
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# 같은 기능, 다른 문법:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [17]:
# 두 텐서 간의 행렬 곱(matrix multiplication) 계산
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# 같은 기능, 다른 문법:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


- 바꿔치기(in-place) 연산

In [18]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## NumPy 변환(Bridge)

### 1. 텐서를 NumPy 배열로 변환하기

In [19]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [20]:
# 텐서의 변경사항이 NumPy 배열에 반영됨
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### 2. NumPy 배열을 텐서로 변환하기

In [21]:
n = np.ones(5)
t = torch.from_numpy(n)

# NumPy 배열의 변경사항이 텐서에 반영됨
np.add(n, 1, out = n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
